---
title: "Impact of national health insurance on health services utilization in Lao People's Democratic Republic (Lao PDR): a quasi-experimental evaluation using longitudinal administrative data"
author: "Sekeun Daniel Yu (yus109@mcmaster.ca), Michel Grignon, Godefroy Emmanuel Guindon, Jean-Éric Tarride"
date: "July/2025"

---

```{r knitr, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)

```

# Setup
<br>
```{r setup, echo=TRUE, message=FALSE, results="hide"}

# Set working directory
rm(list = ls(all.names = TRUE))
#install.packages("rstudioapi")
library(rstudioapi)
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
getwd()

# Install and load packages
source("lao_nhi_0_package.r", echo = TRUE)

packageVersion("did")           # 2.1.2
packageVersion("DRDID")         # 1.2.0
packageVersion("fixest")        # 0.12.1
packageVersion("did2s")         # 1.0.2
packageVersion("etwfe")         # 0.5.0
packageVersion("bacondecomp")   # 0.1.1
packageVersion("honestDiD")     # 0.2.6

```
<br>

# Load data
<br>
```{r load, echo=TRUE, message=FALSE, results="hide"}

data.cln <- read_excel("./data export/02_clean_8_cln_m_dl.xlsx") # district
warnings()
str(data.cln)

data <- data.cln

# Check number of districts
data %>%
 filter(faclevel != "PH") %>%
 summarise(count = n_distinct(district))  # total districts; 148

data %>%
 filter(faclevel != "PH", treat == 1) %>%
 summarise(count = n_distinct(district))  # total districts with NHI; 139

data %>%
 group_by(province) %>%
 filter(faclevel != "PH") %>%
 summarise(count = n_distinct(district))

data %>%
 group_by(province, district) %>%
 summarise(n = n()) %>%
 print(n = Inf)

# Drop pilot districts and PH
data <- data %>%
 filter(
   !(province %in% c("15 Xekong")),  # Drop NHI pilot province
   !(district %in% c("1008 Met", "1009 Viangkham", "1011 Mun",
                     "1306 Nong", "1408 Samouay")),  # Drop NHI pilot districts
   !(district %in% c("0201 Phongsali")),  # Drop district without CU5 in Q4/2015
   !str_detect(faclevel, "PH"),  # Remove provincial hospitals
   as.character(month) >= "2015-10-01") # Months to keep

data %>%
 filter(faclevel != "PH", treat == 1) %>%
 summarise(count = n_distinct(district))  # districts in final analyses;
# 129 districts

# Number of health facilities at event = 0
data %>%
 filter(faclevel != "PH", treat == 1) %>%
 filter(event == 0) %>%
 group_by(faclevel) %>%
 summarise(count = n_distinct(district),
           sum = sum(facnum, na.rm = TRUE))
# 129 districts
# (116 district with district hospitals + 13 districts without district hospital)
# (945-116+91 = 920 health centers)

# District with PH or HC only
# PH: XX00
# PSL 0205 Bounnua: HC only
# LNT 0301 Namtha: HC only
# ODX 0401 Xai: HC only
# BKO
# LPG
# HPN 0701 Xamnua: HC only
# XYB 0801 Xainyabouli: HC only
# XKG 0901 Pek: HC only
# VTP
# BKX 1101 Pakxan: HC only
# KMN 1201 Thakhek: HC only
# SVK 1301 Kaysone Phomvihane: HC only
# SRV 1401 Salavan: HC only 
# SEK 1501 Lamam: HC only
# CPS 1601 Pakxe: HC only 
# ATP 1702 Samakhixai: HC only 
# XSB 1801 Anouvong: HC only 

# 1210 Khounkham - excluded in the facility-level analysis but included in district-level analyses

# Excluding these 12 districts with HC only (due to the presence of PH), increases the DID estimates by about 0.05 points.
#data <- subset(data,District!="0205 Bounnua") # HC only
#data <- subset(data,District!="0301 Namtha") # HC only
#data <- subset(data,District!="0401 Xai") # HC only
#data <- subset(data,District!="0701 Xamnua") # HC only
#data <- subset(data,District!="0801 Xainyabouli") # HC only
#data <- subset(data,District!="0901 Pek") # HC only
#data <- subset(data,District!="1201 Thakhek") # HC only
#data <- subset(data,District!="1301 Kaysone Phomvihane") # HC only
#data <- subset(data,District!="1401 Salavan") # HC only
#data <- subset(data,District!="1601 Pakxe") # HC only
#data <- subset(data,District!="1702 Samakhixai") # HC only
#data <- subset(data,District!="1801 Anouvong") # HC only

# Create directories
if(!dir.exists("./output")) {dir.create("./output")}
if(!dir.exists("./output/m_disl")) {dir.create("./output/m_disl")}
outpath <- c("./output/m_disl/")

```
<br>

# Difference-in-differences: Callaway and Sant'Anna (2021)
<br>
```{r csdid, echo=TRUE}

data_g9 <- data %>% 
  filter(as.character(month)>="2015-10-01" & as.character(month)<="2017-09-01",
         province != "01 Vientiane Capital") %>%
  mutate(group = ifelse(group == max(group), 0, group)) %>%
  mutate(treat = ifelse(group == max(group), 0, treat))
head(data_g9)

# Covariates
covariate <- ~facnum + semp + urba + litr + imps

outname <- c(
  # count
  "opo5", "opu5", "ipo5", "ipu5", "ipday", "del",
  # rate
  "opo5r", "opu5r", "ipo5r", "ipu5r", "iplos", "delr")

for (i in 1:length(outname)) {

set.seed(55555)

# ------------------------------------------------------------------------------
# Varying pre-period
# ------------------------------------------------------------------------------

print(outname[i])

# Base
v <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
            gname = "group", control_group = "notyettreated",
            base_period = "varying",  # reference point varies for pre-NHI period
            est_method = "dr",  # w/o covariate -> outcome regression
            xformla = NULL, panel = TRUE, bstrap = TRUE, cband = TRUE,
            data = data_g9)
glance(v)
v
warnings()

# SE clustered at provincial level
v.cls <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                gname = "group", control_group = "notyettreated",
                base_period = "varying",  # reference point varies for pre-NHI period
                est_method = "dr", clustervars = "pnum",
                xformla = NULL, panel = TRUE, bstrap = TRUE, 
                cband = TRUE, data = data_g9)
glance(v.cls)
v.cls
warnings()

# w/ covariates, base
vc <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
             gname = "group", control_group = "notyettreated",
             base_period = "varying",  # varying reference point
             est_method = "dr",
             xformla = covariate, panel = TRUE, bstrap = TRUE, 
             cband = TRUE, data = data_g9)
glance(vc)
vc
warnings()

# w/ covariates, SE clustered at provincial level 
vc.cls <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                 gname = "group", control_group = "notyettreated",
                 base_period = "varying",  # varying reference point
                 est_method = "dr", clustervars = "pnum",
                 xformla = covariate, panel = TRUE, bstrap = TRUE, 
                 cband = TRUE, data = data_g9)
glance(vc.cls)
vc.cls
warnings()

# w/ covariates, SE clustered at provincial level, last cohort
vc.clslast <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                     gname = "group", control_group = "nevertreated",
                     base_period = "varying",  # varying reference point
                     est_method = "dr", clustervars = "pnum",
                     xformla = covariate, panel = TRUE, bstrap = TRUE, 
                     cband = TRUE, data = data_g9)
glance(vc.clslast)
vc.clslast
warnings()

# w/ covariates, SE clustered at provincial level + anticipation = 1
vc.clsant1 <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                     gname = "group", control_group = "notyettreated",
                     base_period = "varying",  # varying reference point
                     est_method = "dr", anticipation = 1, clustervars = "pnum",
                     xformla = covariate, panel = TRUE, bstrap = TRUE, 
                     cband = TRUE, data = data_g9)
glance(vc.clsant1)
vc.clsant1
warnings()

# ------------------------------------------------------------------------------
# Universal pre-period
# ------------------------------------------------------------------------------

# Base
u <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
            gname = "group", control_group = "notyettreated",
            base_period = "universal",  # reference point fixed for pre-NHI period
            est_method = "dr",
            xformla = NULL, panel = TRUE, bstrap = TRUE, 
            cband = TRUE, data = data_g9)
glance(u)
u
warnings()

# SE clustered at provincial level
u.cls <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                gname = "group", control_group = "notyettreated",
                base_period = "universal",  # reference point fixed for pre-NHI period
                est_method = "dr", clustervars = "pnum",
                xformla = NULL, panel = TRUE, bstrap = TRUE, 
                cband = TRUE, data = data_g9)
glance(u.cls)
u.cls
warnings()

# w/ covariates, Universal pre-period
uc <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
             gname = "group", control_group = "notyettreated",
             base_period = "universal",  # fixed reference point
             est_method = "dr",
             xformla = covariate, panel = TRUE, bstrap = TRUE, 
             cband = TRUE, data = data_g9)
glance(uc)
uc
warnings()

# w/ covariates, SE clustered at provincial level
uc.cls <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                 gname = "group", control_group = "notyettreated",
                 base_period = "universal",  # fixed reference point
                 est_method = "dr", clustervars = "pnum",
                 xformla = covariate, panel = TRUE, bstrap = TRUE, 
                 cband = TRUE, data = data_g9)
glance(uc.cls)
uc.cls
warnings()

# w/ covariates, SE clustered at provincial level, last cohort
uc.clslast <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                     gname = "group", control_group = "nevertreated",
                     base_period = "universal",  # fixed reference point
                     est_method = "dr", clustervars = "pnum",
                     xformla = covariate, panel = TRUE, bstrap = TRUE, 
                     cband = TRUE, data = data_g9)
glance(uc.clslast)
uc.clslast
warnings()

# w/ covariates, SE clustered at provincial level + anticipation = 1
uc.clsant1 <- att_gt(yname = outname[i], tname = "time", idname = "dnum",
                     gname = "group", control_group = "notyettreated",
                     base_period = "universal",  # fixed reference point
                     est_method = "dr", anticipation = 1, clustervars = "pnum",
                     xformla = covariate, panel = TRUE, bstrap = TRUE, 
                     cband = TRUE, data = data_g9)
glance(uc.clsant1)
uc.clsant1
warnings()

listv <- c("v", "v.cls", 
           "vc", "vc.cls", "vc.clslast", "vc.clsant1")
attgt_list_v <- lapply(listv, get)

listu <- c("u", "u.cls", 
           "uc", "uc.cls", "uc.clslast", "uc.clsant1")
attgt_list_u <- lapply(listu, get)

# ------------------------------------------------------------------------------
# Tidy the results and export to Excel file
# ------------------------------------------------------------------------------

# preevent <- data_g9 %>%
#  filter(group > 0 & event == -1) %>%  # only treated units and event time -1
#  mutate(avgunit = mean(opo5r)) %>%  # simple average of units
#  group_by(group) %>%  # grouping to reflect group-time ATT
#  mutate(avggrp = mean(opo5r)) %>% ungroup() %>%  # average of units by group
#  dplyr::select(c("group", "avgunit", "avggrp")) %>%
#  mutate(avggrp2old = mean(avggrp)) %>%  # this gets weighted by # of groups
#  unique  # -> this output is the same as CS weight averaging method

outn <- rlang::sym(outname[i])

preevent <- data_g9 %>%
 filter(group > 0 & event == -1) %>%  # only treated units, event time -1, (excl. G0, G9)
 mutate(avgunit = mean(!!outn, na.rm = TRUE)) %>%  # simple average of units
 group_by(group) %>%  # grouping to reflect group-time ATT
 mutate(avggrp = mean(!!outn, na.rm = TRUE)) %>% ungroup() %>%  # average of units by group
 dplyr::select(c("group", "avgunit", "avggrp")) %>%
 # mutate(avgdyn = mean(avggrp)) %>%  # averaging of averages # same weighted avg output
 unique

u.group <- unique(data_g9$group) # unique group
u.group <- sort(u.group)[-1] # remove untreated
n.group <- sapply(u.group, function(gg) nrow(subset(data_g9, group == gg))) # number of group
ngroup.mat <- as_tibble(cbind(u.group, n.group))
colnames(ngroup.mat) <- c("group", "n.group")

preevent <- preevent %>%
 left_join(ngroup.mat, by = "group") %>%
 mutate(weight = n.group / sum(n.group),
        avgdyn = sum(avggrp * weight)) # weighted avg
  
attgt_tidy_v <- list()
for (j in 1:length(listv)) {
 attgt_tidy_v[[j]] <- tidy(attgt_list_v[[j]])
 attgt_tidy_v[[j]]$ptapval <- c(attgt_list_v[[j]]$Wpval)
 attgt_tidy_v[[j]]$name <- listv[j]
 attgt_tidy_v[[j]] <- left_join(attgt_tidy_v[[j]], preevent, by = c("group"))
 attgt_tidy_v[[j]]$change <- attgt_tidy_v[[j]]$estimate / attgt_tidy_v[[j]]$avggrp
 # baseline utilization is t = -1. Not correct for anticipation effect results
}

attgt_tidy_v_frame <- do.call(rbind, attgt_tidy_v)
attgt_tidy_v_frame$pretrendtype <- "varying"

attgt_tidy_u <- list()
for (j in 1:length(listu)) {
 attgt_tidy_u[[j]] <- tidy(attgt_list_u[[j]])
 attgt_tidy_u[[j]]$ptapval <- c(attgt_list_u[[j]]$Wpval)
 attgt_tidy_u[[j]]$name <- listu[j]
 attgt_tidy_u[[j]] <- left_join(attgt_tidy_u[[j]], preevent, by = c("group"))
 attgt_tidy_u[[j]]$change <- attgt_tidy_u[[j]]$estimate / attgt_tidy_u[[j]]$avggrp
 # baseline utilization is t = -1. Not correct for anticipation effect results
}

attgt_tidy_u_frame <- do.call(rbind, attgt_tidy_u)
attgt_tidy_u_frame$pretrendtype <- "fixed"

attgt_tidy_frame <- rbind(attgt_tidy_v_frame, attgt_tidy_u_frame)
attgt_tidy_frame$outcome <- outname[i]

write_xlsx(attgt_tidy_frame,
           paste0(outpath, outname[i], "_attgt", ".xlsx"))

# ------------------------------------------------------------------------------
# Aggregate the gt-ATT's by desired dimension
# ------------------------------------------------------------------------------

# Varying period
sim_v <- list()  # single treatment effect
aggte_sim_v <- list()
for (k in 1:length(attgt_list_v)) {
 sim_v[[k]] <- aggte(attgt_list_v[[k]], type = "simple", na.rm = TRUE)
 print(sim_v[[k]])
 warnings()
 aggte_sim_v[[k]] <- tidy(sim_v[[k]])
 aggte_sim_v[[k]]$name <- listv[k]
}

aggte_sim_v_frame <- do.call(rbind, aggte_sim_v)
aggte_sim_v_frame <- aggte_sim_v_frame %>%
 mutate(pretrendtype = "varying",
        outcome = outname[i])

grp_v <- list()  # group specific treatment effect
aggte_grp_v <- list()
for (k in 1:length(attgt_list_v)) {
 grp_v[[k]] <- aggte(attgt_list_v[[k]], type = "group", na.rm = TRUE)
 print(grp_v[[k]])
 warnings()
 aggte_grp_v[[k]] <- tidy(grp_v[[k]])
 aggte_grp_v[[k]]$name <- listv[k]
}

aggte_grp_v_frame <- do.call(rbind, aggte_grp_v)
preevent$group  <- as.character(preevent$group)

aggte_grp_v_frame <- aggte_grp_v_frame %>%
 left_join(preevent, by = c("group")) %>%
 mutate(change = estimate / avggrp,
        pretrendtype = "varying",
        outcome = outname[i])

# No event time balancing
dyn_v <- list() # dynamic treatment effect (event study)
aggte_dyn_v <- list()

for (k in 1:length(attgt_list_v)) {
  dyn_v[[k]] <- aggte(attgt_list_v[[k]], type = "dynamic", 
                      balance_e = NULL, na.rm = TRUE)
  print(dyn_v[[k]])
  warnings()
  
  dyn_frame <- tidy(dyn_v[[k]]) %>% 
    mutate(overall.att = dyn_v[[k]]$overall.att,
           overall.se = dyn_v[[k]]$overall.se,
           overall.conf.low = overall.att - qnorm(0.975) * overall.se,
           overall.conf.high = overall.att + qnorm(0.975) * overall.se,
           group = ifelse(event.time < 0, "Pre-NHI", "Post-NHI"),
           name = listv[k])      
  aggte_dyn_v[[k]] <- dyn_frame
}

aggte_dyn_v_frame <- do.call(rbind, aggte_dyn_v)
aggte_dyn_v_frame <- aggte_dyn_v_frame %>%
 mutate(avgunit = unique(preevent$avgunit),
        avgdyn = unique(preevent$avgdyn),
        change = estimate / avgdyn,
        overall.change = overall.att / avgdyn,
        pretrendtype = "varying",
        outcome = outname[i])

# Event time balancing: drop groups not exposed to at least 8 months (e=0-7)
dyn_v_b <- list() # dynamic treatment effect (event study)
aggte_dyn_v_b <- list()

for (k in 1:length(attgt_list_v)) {
 dyn_v_b[[k]] <- aggte(attgt_list_v[[k]], type = "dynamic", 
                       balance_e = 7, na.rm = TRUE)
 print(dyn_v_b[[k]])
 warnings()
 
 dyn_frame_b <- tidy(dyn_v_b[[k]]) %>%
   mutate(overall.att = dyn_v_b[[k]]$overall.att,
          overall.se = dyn_v_b[[k]]$overall.se,
          overall.conf.low = overall.att - qnorm(0.975) * overall.se,
          overall.conf.high = overall.att + qnorm(0.975) * overall.se,
          group = ifelse(event.time < 0, "Pre-NHI", "Post-NHI"),
          name = listv[k])
 aggte_dyn_v_b[[k]] <- dyn_frame_b
}

aggte_dyn_v_frame_b <- do.call(rbind, aggte_dyn_v_b)
aggte_dyn_v_frame_b <- aggte_dyn_v_frame_b %>%
 mutate(avgunit = unique(preevent$avgunit),
        avgdyn = unique(preevent$avgdyn),
        change = estimate / avgdyn,
        overall.change = overall.att / avgdyn,
        pretrendtype = "varying",
        outcome = outname[i])

# Universal, fixed period
sim_u <- list() # single treatment effect
aggte_sim_u <- list()
for (k in 1:length(attgt_list_u)) {
 sim_u[[k]] <- aggte(attgt_list_u[[k]], type = "simple", na.rm = TRUE)
 print(sim_u[[k]])
 warnings()
 aggte_sim_u[[k]] <- tidy(sim_u[[k]])
 aggte_sim_u[[k]]$name <- listu[k]
}

aggte_sim_u_frame <- do.call(rbind, aggte_sim_u)
aggte_sim_u_frame <- aggte_sim_u_frame %>%
 mutate(pretrendtype = "fixed",
        outcome = outname[i])

grp_u <- list() # group specific treatment effect
aggte_grp_u <- list()
for (k in 1:length(attgt_list_u)) {
        grp_u[[k]] <- aggte(attgt_list_u[[k]], type = "group", na.rm = TRUE)
        print(grp_u[[k]])
        warnings()
        aggte_grp_u[[k]] <- tidy(grp_u[[k]])
        aggte_grp_u[[k]]$name <- listu[k]
}

aggte_grp_u_frame <- do.call(rbind, aggte_grp_u)
preevent$group  <- as.character(preevent$group)
aggte_grp_u_frame <- aggte_grp_u_frame %>%
 left_join(preevent, by = c("group")) %>%
 mutate(change = estimate / avggrp,
        pretrendtype = "fixed",
        outcome = outname[i])

# No event time balancing
dyn_u <- list() # dynamic treatment effect (event study)
aggte_dyn_u <- list()

for (k in 1:length(attgt_list_u)) {
  dyn_u[[k]] <- aggte(attgt_list_u[[k]], type = "dynamic", 
                      balance_e = NULL, na.rm = TRUE)
  print(dyn_u[[k]])
  warnings()

  dyn_frame <- tidy(dyn_u[[k]]) %>%
    mutate(overall.att = dyn_u[[k]]$overall.att,
           overall.se = dyn_u[[k]]$overall.se,
           overall.conf.low = overall.att - qnorm(0.975) * overall.se,
           overall.conf.high = overall.att + qnorm(0.975) * overall.se,
           group = ifelse(event.time < 0, "Pre-NHI", "Post-NHI"),
           name = listu[k])
  aggte_dyn_u[[k]] <- dyn_frame
}

aggte_dyn_u_frame <- do.call(rbind, aggte_dyn_u)
aggte_dyn_u_frame <- aggte_dyn_u_frame %>%
 mutate(avgunit = unique(preevent$avgunit),
        avgdyn = unique(preevent$avgdyn),
        change = estimate / avgdyn,
        overall.change = overall.att / avgdyn,
        pretrendtype = "fixed",
        outcome = outname[i])

# Event time balancing: drop groups not exposed to at least 8 months (e=0-7)
dyn_u_b <- list() # dynamic treatment effect (event study)
aggte_dyn_u_b <- list()

for (k in 1:length(attgt_list_u)) {
  dyn_u_b[[k]] <- aggte(attgt_list_u[[k]], type = "dynamic", 
                        balance_e = 7, na.rm = TRUE)
  print(dyn_u_b[[k]])
  warnings()
  
  dyn_frame_b <- tidy(dyn_u_b[[k]]) %>%
    mutate(
      overall.att = dyn_u_b[[k]]$overall.att,
      overall.se = dyn_u_b[[k]]$overall.se,
      overall.conf.low = overall.att - qnorm(0.975) * overall.se,
      overall.conf.high = overall.att + qnorm(0.975) * overall.se,
      group = ifelse(event.time < 0, "Pre-NHI", "Post-NHI"),
      name = listu[k])
  aggte_dyn_u_b[[k]] <- dyn_frame_b
}

aggte_dyn_u_frame_b <- do.call(rbind, aggte_dyn_u_b)
aggte_dyn_u_frame_b <- aggte_dyn_u_frame_b %>%
 mutate(avgunit = unique(preevent$avgunit),
        avgdyn = unique(preevent$avgdyn),
        change = estimate / avgdyn,
        overall.change = overall.att / avgdyn,
        pretrendtype = "fixed",
        outcome = outname[i])

aggte_sim_frame <- rbind(aggte_sim_v_frame, aggte_sim_u_frame)
aggte_grp_frame <- rbind(aggte_grp_v_frame, aggte_grp_u_frame)
aggte_dyn_frame <- rbind(aggte_dyn_v_frame, aggte_dyn_u_frame)
aggte_dyn_frame_b <- rbind(aggte_dyn_v_frame_b, aggte_dyn_u_frame_b)

write_xlsx(aggte_sim_frame,
           paste0(outpath, outname[i], "_aggte_sim", ".xlsx"))

write_xlsx(aggte_grp_frame,
           paste0(outpath, outname[i], "_aggte_grp", ".xlsx"))

write_xlsx(aggte_dyn_frame,
           paste0(outpath, outname[i], "_aggte_dyn", ".xlsx"))

write_xlsx(aggte_dyn_frame_b,
           paste0(outpath, outname[i], "_aggte_dyn_b", ".xlsx"))
}

```
<br>

# I: Controlled interrupted time series analysis (monthly)
<br>
```{r its, eval=FALSE, include=FALSE}

# Random effects by province

data.its <- data
drop.list <- c("0101 Chanthabouli", "0102 Sikhottabong", 
               "0103 Xaisettha", "0109 Pakngum")
data.its <- filter(data.its, !(district %in% drop.list)) # drop bad controls

p_by_g_m <- data.its %>%
 group_by(group) %>%
 dplyr::select(group, province) %>%
 unique() %>%
 arrange(group) %>%
 group_by(group) %>%
 summarize(province = toString(province))
p_by_g_m

p_by_g_n <- data.its %>%
 group_by(group) %>%
 dplyr::select(group, province, district) %>%
 unique() %>%
 arrange(group) %>%
 group_by(group) %>%
 summarize(dnum = n_distinct(district))
p_by_g_n

# intv: dummy for control (0) / treatment (1)
# post: dummy for pre (0) / post (1)
# event: time

# Estimation equation
# intercept             b0: control group intercept
# event                 b1: time trend
# post                  b2: control group level change, if any
# post x event          b3: control group slope change, if any
# intv                  b4: treatment (intercept difference, pre-NHI period)
# intv x event          b5: pre-NHI slope change (parallel trends)
#                           if not statistically sig. -> trend not different
# intv x post           b6: post-NHI level change differences
# intv x event x post   b7: post-NHI slope change differences

# Monthly, Oct/2015 - Jun/2018
# - Group 0: 01 VTP
# - Group 10: 17 ATP
# - Group 11: 03 LNT, 18 XSB
# - Group 15: 14 SRV
# - Group 16: 11 BKX, 07 HPN, 09 XKG
# - Group 17: 04 ODX, 02 PSL
# - Group 24: 13 SVK, 16 CPS
# - Group 25: 05 BKO, 12 KMN, 06 LPG, 08 XYB, 10 VTP

# ------------------------------------------------------------------------------
# ITS Model 1-2
# Data frequency: Monthly
# Treatment: Early-treated districts (group 10, 11, 15, 16, 17)
# Control: Last-treated districts (group 25)
# # Period: 8 months before/after (Oct/2015 - Jun/2018)
# ------------------------------------------------------------------------------

# Intervention group is group 10, 11, 15, 16, 17
pnumlist <- unique(data.its$pnum)  # run model for each province
pnumlist <- pnumlist[pnumlist != 1 & !(pnumlist %in% c(5, 6, 8, 10, 12, 13, 16))]
# drop group 0 (VTC), group 24 (13,16), group 25 (5, 6, 8, 10, 12)

its_m1m <- list()

for (j in pnumlist) {
 data.its.m <- data.its %>%  # treatment: 2, 3, 4, 7, 9, 11, 14, 17, 18
  filter(pnum == j | pnum %in% c(5, 6, 8, 10, 12)) %>%  # controls: 5, 6, 8, 10, 12
  mutate(gmin = min(group),
         event = time - gmin,
         post = as.integer(event >= 0),
         post_event = post * event,
         gmax = max(group),
         intv = as.integer(group != gmax),  # zero if group 9
         intv_event = intv * event,
         intv_post = intv * post,
         intv_event_post = intv * event * post) %>%
  filter(event >= -8 & event <= 7)  # -8~-1 is pre-NHI, 0~7 is post-NHI

 min(data.its.m$event)
 max(data.its.m$event)
 
 outname <- c("opo5r", "ipo5r", "opu5r", "ipu5r", "iplos", "delr")
 its_df <- list()
 
 for (i in 1:length(outname)) {
  set.seed(55555)
  
  # District random effects
  x1 <- c("event", "post", "post_event", "intv",
          "intv_event", "intv_post", "intv_event_post",
          "facnum")
  formula1 <- reformulate(c(x1), response = outname[i])
  its_m <- plm(formula1, data = data.its.m,
               index = c("dnum"), model = "random")
  
  summary(its_m)
  its_fit <- lmtest::coeftest(its_m, vcovHC(its_m, method = "arellano", type = "HC3"))
  its_fit <- its_fit %>% tidy(conf.int = TRUE)
  its_fit$outcome <- outname[i]
  its_df[[i]] <- its_fit
 }
 
 its_set <- do.call(rbind, its_df)
 its_set$pnum <- j
 its_m1m[[j]] <- its_set
}

its_m1m_all <- do.call(rbind, its_m1m)

# ------------------------------------------------------------------------------
# ITS Model 2-2
# Data frequency: Monthly
# Treatment: All treated districts (group 10, 11, 15, 16, 17, 24, 25)
# Control: Untreated districts (group 0 VTC)
# # Period: 8 months before/after (Oct/2015 - Jun/2018)
# ------------------------------------------------------------------------------

# Intervention group (group 10, 11, 15, 16, 17, 24, 25)
pnumlist <- unique(data.its$pnum)
pnumlist <- pnumlist[pnumlist != 1] # drop group 0 (VTC)

# Control group (untreated districts from group 0 VTC)
# 104 Sisattanak
# 105 Naxaythong
# 106 Xaithani
# 107 Hatxayfong
# 108 Sangthong
# 109 Pakngum

# Outpatient o5: Sisattanak, Naxaythong, Xaithani, Hatxayfong
# Outpatient u5: Xaithani, Sangthong, Pakngum
# Inpatient o5: Sisattanak, Sangthong
# Inpatient u5: Xaithani, Sangthong
# Inpatient day: Sangthong, Pakngum
# Delivery: Xaithani, Sangthong, Pakngum

list_untreated <- list(
  c(104, 105, 106, 107),
  c(106, 108, 109),
  c(104, 108),
  c(106, 108),
  c(107, 108),
  c(106, 108, 109))

its_m2m <- list()

for (j in pnumlist) {

outname <- c("opo5r", "ipo5r", "opu5r", "ipu5r", "iplos", "delr")
its_df <- list()

  for (i in 1:length(outname)) {
  set.seed(55555)
    
    data.its.m <- data.its %>%
      filter(pnum == j | dnum %in% list_untreated[[i]]) %>%  # controls: select dnum
      mutate(
        gnum = first(group[pnum == j]),
        event = time - gnum,
        post = as.integer(event >= 0),
        post_event = post * event,
        intv = as.integer(pnum != 1),  # zero if VTC
        intv_event = intv * event,
        intv_post = intv * post,
        intv_event_post = intv * event * post) %>%
      filter(event >= -8 & event <= 7)  # -8~-1 is pre-NHI, 0~7 is post-NHI
 
    min(data.its.m$event)
    max(data.its.m$event)
 
    # District random effect
    x1 <- c("event", "post", "post_event", "intv",
            "intv_event", "intv_post", "intv_event_post",
            "facnum")
    formula1 <- reformulate(c(x1), response = outname[i])
    its_m <- plm(formula1, data = data.its.m,
                 index = c("dnum"), model = "random")
    summary(its_m)
    
    its_fit <- lmtest::coeftest(its_m, vcovHC(its_m, method = "arellano", 
                                              type = "HC3"))
    its_fit <- its_fit %>% tidy(conf.int = TRUE)
    its_fit$outcome <- outname[i]
    its_df[[i]] <- its_fit
    }

its_set <- do.call(rbind, its_df)
its_set$pnum <- j
its_m2m[[j]] <- its_set
}

its_m2m_all <- do.call(rbind, its_m2m)

# ------------------------------------------------------------------------------
# ITS Model 3-2
# Data frequency: Monthly
# Treatment: Early-treated districts (group 10, 11, 15, 16, 17)
# Control: Untreated districts (group 0 VTC)
# # Period: 8 months before/after (Oct/2015 - Jun/2018)
# ------------------------------------------------------------------------------

# Intervention group (group 10, 11, 15, 16, 17 only)
pnumlist <- unique(data.its$pnum)
pnumlist <- pnumlist[pnumlist != 1 & !(pnumlist %in% c(5, 6, 8, 10, 12, 13, 16))]
# drop group 0 (VTC) and group 24 (13, 16) and group 25 (5, 6, 8, 10, 12)

# Control group (untreated districts from group 0 VTC)
# 104 Sisattanak
# 105 Naxaythong
# 106 Xaithani
# 107 Hatxayfong
# 108 Sangthong
# 109 Pakngum

# Outpatient o5: Sisattanak, Naxaythong, Xaithani, Hatxayfong
# Outpatient u5: Xaithani, Sangthong, Pakngum
# Inpatient o5: Sisattanak, Sangthong
# Inpatient u5: Xaithani, Sangthong
# Inpatient day: Sangthong, Pakngum
# Delivery: Xaithani, Sangthong, Pakngum

list_untreated <- list(
  c(104, 105, 106, 107),
  c(106, 108, 109),
  c(104, 108),
  c(106, 108),
  c(107, 108),
  c(106, 108, 109))

its_m3m <- list()

for (j in pnumlist) {

outname <- c("opo5r", "ipo5r", "opu5r", "ipu5r", "iplos", "delr")
its_df <- list()

  for (i in 1:length(outname)) {
    set.seed(55555)
    
    data.its.m <- data.its %>%
      filter(pnum == j | dnum %in% list_untreated[[i]]) %>% # controls: select dnum
      mutate(
        gnum = first(group[pnum == j]),
        event = time - gnum,
        post = as.integer(event >= 0),
        post_event = post * event,
        intv = as.integer(pnum != 1), # zero if VTC
        intv_event = intv * event,
        intv_post = intv * post,
        intv_event_post = intv * event * post) %>%
      filter(event >= -8 & event <= 7) # -8~-1 is pre-NHI, 0~7 is post-NHI
    
    min(data.its.m$event)
    max(data.its.m$event)
    
    # District random effect
    x1 <- c("event", "post", "post_event", "intv", 
            "intv_event", "intv_post", "intv_event_post", 
            "facnum")
    formula1 <- reformulate(c(x1), response = outname[i])
    its_m <- plm(formula1, data = data.its.m, index = c("dnum"), model = "random")
    summary(its_m)
    its_fit <- lmtest::coeftest(its_m, vcovHC(its_m, method = "arellano", type = "HC3"))
    its_fit <- its_fit %>% tidy(conf.int = TRUE)

    its_fit$outcome <- outname[i]
    its_df[[i]] <- its_fit
    }

its_set <- do.call(rbind, its_df)
its_set$pnum <- j
its_m3m[[j]] <- its_set
}

its_m3m_all <- do.call(rbind, its_m3m)

# Combine all frames
its_all <- list()
its_all[[1]] <- its_m1m_all
its_all[[2]] <- its_m2m_all
its_all[[3]] <- its_m3m_all

# ------------------------------------------------------------------------------
# Meta-Analysis
# ------------------------------------------------------------------------------

meta_summary <- list()
meta_summary_df <- list()
meta_listname <- c("model_1_m", "model_2_m", "model_3_m")

for (j in 1:length(its_all)) {
 for (i in 1:length(outname)) {
  set.seed(55555)
   
  its_meta_sub <- its_all[[j]] %>% filter(outcome == outname[i])
  its_meta_b5 <- its_meta_sub %>% filter(term == "intv_event")
  its_meta_b6 <- its_meta_sub %>% filter(term == "intv_post")
  its_meta_b7 <- its_meta_sub %>% filter(term == "intv_event_post")

  its_b5 <- metagen(TE = estimate,
                    seTE = std.error,
                    studlab = pnum,
                    data = its_meta_b5,
                    random = TRUE,
                    method.tau = "REML",
                    hakn = TRUE)
  summary(its_b5)

  b5_summary <- cbind.data.frame(its_b5$TE.random,
                                 its_b5$lower.random,
                                 its_b5$upper.random,
                                 its_b5$statistic.random,
                                 its_b5$pval.random,
                                 "Parallel trend (beta5)")
  colnames(b5_summary) <- c("estimate", "lowerci", "upperci", "tstat", 
                            "pval", "label")

  its_b6 <- metagen(TE = estimate,
                    seTE = std.error,
                    studlab = pnum,
                    data = its_meta_b6,
                    random = TRUE,
                    method.tau = "REML",
                    hakn = TRUE)
  summary(its_b6)

  b6_summary <- cbind.data.frame(its_b6$TE.random,
                                 its_b6$lower.random,
                                 its_b6$upper.random,
                                 its_b6$statistic.random,
                                 its_b6$pval.random,
                                 "DID of level (beta6)")
  colnames(b6_summary) <- c("estimate", "lowerci", "upperci", "tstat", 
                            "pval", "label")

  its_b7 <- metagen(TE = estimate,
                    seTE = std.error,
                    studlab = pnum,
                    data = its_meta_b7,
                    random = TRUE,
                    method.tau = "REML",
                    hakn = TRUE)
  summary(its_b7)

  b7_summary <- cbind.data.frame(its_b7$TE.random,
                                 its_b7$lower.random,
                                 its_b7$upper.random,
                                 its_b7$statistic.random,
                                 its_b7$pval.random,
                                 "DID of slope (beta7)")
  colnames(b7_summary) <- c("estimate", "lowerci", "upperci", "tstat", 
                            "pval", "label")

  combined <- rbind(b5_summary, b6_summary, b7_summary)
  combined$outcome <- outname[i]
  meta_summary[[i]] <- combined
 }
  
 meta_temp <- do.call(rbind, meta_summary)
 meta_temp$dataset <- meta_listname[j]
 meta_summary_df[[j]] <- meta_temp
}

its_meta_final_m <- do.call(rbind, meta_summary_df) 
# %>%
#   mutate(label = factor(label, 
#                         levels = c("DID of slope (beta7)", 
#                                    "DID of level (beta6)", 
#                                    "Parallel trend (beta5)")),
#          model = factor(dataset, 
#                            levels = c("model_3_m", "model_2_m", "model_1_m"),
#                            labels = c("Never treated 456, monthly", 
#                                       "Never treated, monthly", 
#                                       "Last treated, monthly")))

write_xlsx(its_meta_final_m, "./output/m_disl/cits_m.xlsx")

```
